"""initial migration

Revision ID: 5b779a96e226
Revises: 
Create Date: 2025-02-23 15:14:04.271815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b779a96e226'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_files',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'file_uuid')
    )
    op.create_table('message_files',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'file_uuid')
    )
    op.drop_table('messages_files')
    op.drop_table('tickets_files')
    op.add_column('messages', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('tickets', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'deleted')
    op.drop_column('messages', 'deleted')
    op.create_table('tickets_files',
    sa.Column('ticket_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_uuid', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='tickets_files_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'file_uuid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('messages_files',
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_uuid', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='messages_files_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'file_uuid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('message_files')
    op.drop_table('ticket_files')
    # ### end Alembic commands ###
